version: "3.7"
services:

  agent-app:
    image: agent-app
    container_name: agent-app
    build: 
      context: ./MonolitApp
      dockerfile: Dockerfile
    tty: true
    restart: on-failure
    networks:
      - static-network
    ports:
      - 8083:8083
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_DOMAIN: mysql
      DATABASE_SCHEMA: rent_a_car?createDatabaseIfNotExist=true&serverTimezone=UTC
    depends_on: 
      - mysql
  
  mysql:
    image: mysql:8.0.19
    container_name: mysql
    restart: always
    networks:
      - static-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rent_a_car

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16